### ISSUE TITLE
select Candidate Orthologous Genes (OGs) from transcript of transcriptomes

### ISSUE THREAD

**Issue by Dream-sugar** [BIONF/fDOG#33]
Dear Professor：
       I found through literature review that HaMStR can identify orthologous clusters from genomes or transcriptomes(http://www.deep-phylogeny.org/hamstr/) by performed with strict parameters (-hmmset = magnoliophyta_hmmer3, -representative, -strict, -eval_limit = 0.00001, and -rbh). Most of those paper used the perl script (perl hamstrsearch_local-hmmer3.v8.pl), I did not found it in the package of fDOG and found hamstr.pl in https://github.com/BIONF/HaMStR/blob/master/h1s/bin/hamstr.pl.  So I would like to take this opportunity to ask you a few questions. fDOG can do same work like this paper (https://doi.org/10.1016/j.xplc.2023.100595) to select Candidate Orthologous Genes (OGs) from transcript of transcriptomes, and which script can do it?

**Comment by Dream-sugar** [comment]
Hi Vinh
Thank you very much for your reply, I had download it. However, I have questions about how to search for homologous genes simultaneously from different transcripts of the same sample or different samples.I saw that the Input  for fDOG is a single FASTA file. If I have many different samples of transcriptome [.pep.fa](files composed of different transcripts[.fasta]), can I only search each transcript [.fasta] once if I want to achieve homologous gene search through fDOG? then  merge several fDOG outputs into a single output? In addition, can i use the custom core_orthologs to search Candidate Orthologous Genes (OGs) from transcript of transcriptomes?
Sincerely,
Jing Zhao

**Comment by trvinh** [comment]
Hi Jing Zhao,
Please check [this wiki page](https://github.com/BIONF/fDOG/wiki/How-fDOG-works) to see how fDOG works. There are 2 main use-cases. 
1) Searching orthologs for **ONE seed sequence**. Here the input for fDOG is only a single fasta file (fasta file that contains only 1 sequence). In this case, fDOG will perform the full pipeline including the core ortholog groups compilation and the extended ortholog search. 
1b) Searching orthologs for **MUILTIPLE seed sequences**. This is the extended version of case (1). fDOG is able to run with multiple seed sequences in parallel. This doesn't mean, that it accepts a fasta file with multiple sequences, but the user needs to input a folder that contains several single fasta files. See [this post](https://github.com/BIONF/fDOG/wiki/Use-standalone-version). 
2) Extending the **existing ortholog groups**. In this case, the user already has his/her own ortholog groups, and he/she wants to extend those groups with the orthologs from other species or gene sets. fDOG will skip the core ortholog groups compilation and only run the ortholog search using the HMM profiles build from the existing ortholog groups. This works similarly to the original HaMStR. See [this post](https://github.com/BIONF/fDOG/wiki/Use-cases#Extend-existing-orthologous-groups). 

So, if you want to start from scratch, the first use-case is what you need. But if you want to do only as same as HaMStR, I think you mentioned the second approach. If it is the case, please [contact me via email](mailto:tran@bio.uni-frankfurt.de) with detailed information (e.g. which taxa should be part of your starting ortholog groups), may be I can help you to prepare the data you need. 
I hope that can help!
Regards,
Vinh

**Comment by wojiaonjp** [comment]
Hi Vinh, if my transcriptome data scale has reached phylum, how should I choose the "--refspec" here?
Sincerely,
jiangping Ni

**Comment by trvinh** [comment]
> Hi Vinh, if my transcriptome data scale has reached phylum, how should I choose the "--refspec" here? Sincerely, 

Hi jiangping Ni,
the reference species (specified with `--refspec`) is one of the species in the dataset. You can choose it, for example by:
- selecting the most closely related species to your search taxa (taxa in which you want to search for orthologs)
- selecting the most abundant species in your taxon set
- selecting the species with the most information (such as species with the best/complete assembly, or best annotation, ...)
- etc.

You can use one or combine different criteria to choose your reference species. 
Best,
Vinh

**Comment by wojiaonjp** [comment]
Hi Vinh:
Thank you very much for your reply. However, I still seem to have trouble understanding the working principle here. According to your previous response, I used my own ortholog groups sequences as input, and hmm file was built using hmmbuild for these ortholog groups sequences. I have already added all transcriptomes to fdog/data, and I have selected one of the species from the transcriptomes as the reference species. I found that this way will get orthologous genes and test.extended.fa for all species in fdog/data. I feel like there might be a problem with the choice of --refspec here. Or maybe my understanding or option above is incorrect.I want to know what the --refspec works here.
Thank you for your assistance.
Best regards,
Jiangping Ni

**Comment by trvinh** [comment]
Hi,
fDOG is originally designed for searching orthologs for a single protein. The species to which that protein belongs serves as the reference species. Please prefer to [this post](https://github.com/BIONF/fDOG/wiki/How-fDOG-works) for the workflow of fDOG. In your case, you skipped the first step and started with a HMM profile. A reference species must be chosen because it is required for the reverse blast search to verify the ortholog candidates. To be more precise, fDOG will search for homolog sequences in the reference species for each ortholog candidate. Then, the blast hits will be compared with the seed sequence in the HMM profile. If they passes the reciprocal criteria, the ortholog candidate will be accepted and added into the ortholog group.
I don't know if you also performed the last step, the FAS calculation. In this step, a reference species is also needed in order to identify the seed sequence in each ortholog group (the black dot in the workflow figure). The FAS scores of each ortholog will be calculated against that seed sequence.
I hope it can help!
Regards,
Vinh

**Comment by wojiaonjp** [comment]
Thank you for your patient response.
As Jing Zhao initially mentioned, if I want to replicate the work in this paper (https://doi.org/10.1016/j.xplc.2023.100595), this study uses low-copy OGs from nine species of Solanaceae as queries to search for homologous sequences in 180 Solanaceae species and all outgroups. If the genomes of these nine Solanaceae species are of relatively high quality and their distribution of evolutionary relationships is relatively even, it would not be appropriate to choose only one species as the reference species. In this case, how should I choose the "--refspec"? Can I separate these homologous gene sequences by species and OG and select sequences corresponding species as refspec to search for orthologous sequences?
Sincerely,
jiangping Ni

**Comment by trvinh** [comment]
Hi,
please see my [answer above](https://github.com/BIONF/fDOG/issues/33#issuecomment-1511748256). It is not possible to use all the 9 Solanaceae species for the reverse blast search anymore (it was possible in HaMStR with the option `-strict`). That's why you need to choose one of those 9 Solanaceae species as a reference species. If their genomes and gene annotations are equally good, I think your choice of the reference species will not significantly affect the results.
Regards,
Vinh
